jami-fhir-jp-wg/jp-core-v1x

input/fsh/profiles/JP_MedicationRequestBase.fsh

* value[x] only string or CodeableConcept
を
* value[x] only  CodeableConcept
に修正。
CodeableConcept.text に文字列だけを記述することが可能であるため、あえてstring型を選択できるようにしておく必要がない。
なるべくシンプルなほうがよいため。
SWG5
SWG5

修正 Extension: JP_..._InstructionForDispense

---

input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md

1. 「InstructionForDispense」拡張の仕様が古いままだったので、処方データHL7 FHIR記述仕様に合わせて修正
2. 電子処方箋HL7 FHIR仕様→処方データHL7 FHIR記述仕様
3. 参考文献に「処方データHL7 FHIR記述仕様」を追加
SWG5
@skoba 
1. 「InstructionForDispense」拡張の内容が「処方データHL7 FHIR記述仕様」と矛盾がないか
2. 「処方データHL7 FHIR記述仕様」の参照方法が問題ないか

「InstructionForDispense」拡張の仕様が古いままだったので修正

---

input/fsh/searchparameters/JP_Patient_SP.fsh

漢字名・カナ名による検索の型をtoken型からstring型へ修正しました。
SWG1
SWG1
FHIRのname検索では先頭の部分一致でもヒットさせる方針で、完全一致を強制する場合には:exactモディファイアを使います。https://hl7.org/fhir/R4/search.html#string
JPでは完全一致を標準としたいという積極的な意図でtoken型としたということでしたら、詳細について議論させてください。

漢字名、カナ名による検索型がtokenとなっていましたが、オリジナルの検索型と同じstringとしました。

---

input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md

JP_MedicationRequest_Injectionの実装ガイドで「BodyStructure」拡張の記述に不備があったので修正
SWG5
@skoba 
追加した記述が間違っていないか
レンダリングした結果が崩れていないか

「BodyStructure」拡張の記述の不備の修正

---

input/fsh/searchparameters/JP_Patient_SP.fsh
input/includes/markdown-link-references.md
input/pagecontent/group-searchParameter.md

WG1検討の結果、漢字・カナ名称の検索パラメターの利用用途がまだ不明なためJPCoreとしては定義しなくても
よいとの結論になりました。確認を含めてmergeをしていただくようお願いします。
fix #76
SWG1
SWG3
削除により他の影響がないかを確認をお願いします。

漢字、カナ名称検索パラメータの廃止

---

input/intro-notes/StructureDefinition-jp-medication-notes.md
input/intro-notes/StructureDefinition-jp-medicationadministration-injection-notes.md
input/intro-notes/StructureDefinition-jp-medicationadministration-notes.md
input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
input/intro-notes/StructureDefinition-jp-medicationdispense-notes.md
input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md

・バリデーションでOKとなったサンプルインスタンスを実装ガイドに取り込む
・サンプルインスタンスを折り畳みの中に入れると表示が崩れるため、折り畳みを止める
・複数のインスタンスを１つにまとめるのをやめ、インスタンスごとに記述する
SWG5
@skoba 
表示の崩れがないか

サンプルインスタンスを実装ガイドに取り込む

---

input/intro-notes/StructureDefinition-jp-immunization-notes.md

ソースコードのhttp属性を削除
SWG1
SWG5
・httpのURL文字が見にくくなるため。

SWG5 ソースコードのhttp属性を削除

---

input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md

「ePrescription」ではなく「Common」が正解のため、そのように修正する
SWG5
@skoba 
本文の記載内容とURLが一致しているかどうか
#158

「ePrescription」ではなく「Common」が正解のため、そのように修正

---

input/fsh/profiles/JP_MedicationAdministration.fsh
input/fsh/profiles/JP_MedicationRequestBase.fsh

extensionの中で、PurposeがDescriptionと同一のものを削除する。
SWG5
SWG5
・DescriptionとPurposeが一緒のものを削除しました。
→ Clean Sourceを心がけるため、コメントアウトではなく削除しました。gitでは変更内容は変更履歴で追跡できるので。
・DescriptionとPurposeが異なる記述のものは残しています。
fixed #163

swg5 extensionの中で、PurposeがDescriptionと同一のものを削除する

---

input/pagecontent/guide-stringSearch.md

swg1 - 「:exact」指定における異体字の扱い」の結果を反映しました。
SWG1
SWG1
- 変更案が正しく反映できているか。
- 記述内容は十分か。
fixed #81

Issue #81「swg1 - 「:exact」指定における異体字の扱い」の修正。

---

input/fsh/aliases-jpcore.fsh
input/fsh/profiles/JP_Observation_BodyMeasurement.fsh
input/fsh/profiles/JP_Observation_PhysicalExam.fsh
input/includes/markdown-link-references.md
input/intro-notes/StructureDefinition-jp-observation-physicalexam-notes.md
input/pagecontent/group-diagnostic.md
sushi-config.yaml

[#165](https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/165)による修正
SWG2
SWG1
[#165](https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/165)
SWG6（今井先生）との議論により、拡張は使用せずICD-11で表現することとした。

JP_Observation_PhysicalExamプロファイルのbodySiteのExtension定義を削除

---

input/intro-notes/StructureDefinition-jp-allergyintolerance-intro.md
input/intro-notes/StructureDefinition-jp-allergyintolerance-notes.md
input/intro-notes/StructureDefinition-jp-condition-intro.md
input/intro-notes/StructureDefinition-jp-condition-notes.md
input/intro-notes/StructureDefinition-jp-procedure-notes.md

- リンクの表現方法修正
記述方法変更
- 参照元情報の削除
全体会議にて削除する方針となったため。
SWG4
SWG4
内容の確認をお願いします。

swg4 リンクの表現方法修正＆参照元情報の削除

---

input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md

JP_MedicationRequest_Injectionの調剤指示のExtensionの仕様が古いままだったので修正した。
@skoba 
調剤指示のExtensionの記述が最新の仕様と合っているか。
#185

swg5 JP_MedicationRequest_Injectionの調剤指示の記述を修正

---

input/intro-notes/StructureDefinition-jp-encounter-notes.md
input/intro-notes/StructureDefinition-jp-location-notes.md
input/intro-notes/StructureDefinition-jp-organization-notes.md
input/intro-notes/StructureDefinition-jp-patient-notes.md
input/intro-notes/StructureDefinition-jp-practitioner-notes.md
input/intro-notes/StructureDefinition-jp-practitionerrole-notes.md

ss-mix標準ストレージのPDF 1.2fの仕様書のリンクが消えてしまった。
後継と思われる仕様書があったので、付け替えをしました。
swg3
- 付け替えた仕様書が正しいか、仕様的に矛盾を生じないか確認をお願いします。

swg3 ss-mix標準ストレージのPDF 1.2Fが見えなくなった

---

input/fsh/profiles/JP_MedicationRequest.fsh
input/fsh/profiles/JP_MedicationRequestBase.fsh

MedicationRequestで同一Rpグループ内での連番を示すIdentifier[OrderInRp]をMedicationRequestBaseからMedicationRequestに移動した。
SWG5
refs #236

moved identifier[orderinRp], refs #236

---

input/fsh/profiles/JP_Medication.fsh

JP_MedicationでのDrugNo extensionに対する記載がStrengthTypeのものとなっていた。
SWG5
表記の間違い
なし

SWG5 fixed wrong description in JP_Medication

---

input/intro-notes/StructureDefinition-jp-observation-common-notes.md

[石原さんの投稿@Slack](https://hl7fhir-jp-wg.slack.com/archives/CLYGNRWMN/p1660144212075019?thread_ts=1660056194.922719&cid=CLYGNRWMN)
@findex-miyakawa 
fixed #196

JP_Observation_Commonの説明文書からSNOMEDの記述を削除

---

input/fsh/profiles/JP_MedicationRequestBase.fsh

MedicationRequestBaase CodingのCardinality制約を削除
SWG5 
テキストでの記載もあり得るため、Cardinalityの制約を削除した
fixed #312

swg5 MedicationRequestBaase CodingのCardinality制約を削除

---

input/fsh/examples/JP_FamilyMemberHistory_Example.fsh

sexがFamilyMemberHistoryの場合、CodeableConcept型となっているため、Systemが必要になる。
qa.htmlに警告としてあがっていたため、対処。
SWG4

swg4 警告対応code systemの指定

---

input/fsh/profiles/JP_MedicationRequestBase.fsh

maxDose の単位を urn:oid:1.2.392.100495.20.2.101 から JP_MedicationUnitMERIT9_VS に変更
SWG5
関連するwarning の減少
fixed #316

assinged JP_MedicationUnitMERIT9_VS refs #316

---

input/fsh/examples/JP_MedicationRequest_Injection_Example.fsh

警告対策
MedicationRequest_InjectionサンプルCodeSystemにないコードの指定
ワンショットのマスタが無かったため、既にあるマスタに付け替えました。
swg5
- 意図したサンプルになっているか

swg5 MedicationRequest_InjectionサンプルCodeSystemにないコードの指定

---

input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md

投与装置の「使用者定義表0164」が「使用者定義表0162」となっている間違いの修正
SWG5 @skoba 
・定義表の重複が残っていないか
・投与装置の表番号が間違っていないか
fixed #400

投与装置の「使用者定義表0164」が「使用者定義表0162」となっている間違いの修正

---

input/fsh/profiles/JP_MedicationRequest.fsh
input/fsh/profiles/JP_MedicationRequestBase.fsh

バインディング強度をRequired以外を指定した上でValueSetを指定
SWG5 @skoba 
・FSHの書き方として問題ないか
fixed #309

swg5 バインディング強度をRequired以外を指定した上でValueSetを指定

---

input/fsh/profiles/JP_Practitioner.fsh
input/fsh/terminologies/JP_MedicalLicenseCertificate_CS.fsh

麻薬施用者番号の都道府県の記述が多いため、試しに説明文にて回避してみた。
swg3
- 制約を若干弱くするが、施設のOIDの記述も文字列説明に留めているのでよいのでは。
【修正前】
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-practitioner.html#profile
【修正後】
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg3-Practitioner%E3%81%AE%E9%BA%BB%E8%96%AC%E6%96%BD%E7%94%A8%E8%80%85%E7%95%AA%E5%8F%B7%E3%82%92%E3%81%BE%E3%81%A8%E3%82%81%E3%82%8B/StructureDefinition-jp-practitioner.html#profile

swg3 麻薬施用者番号の都道府県の記述が多いため説明文にて回避

---

input/fsh/profiles/JP_DiagnosticReport_LabResult.fsh
input/fsh/profiles/JP_Observation_PhysicalExam.fsh

FixedValue警告回避。0..1のスライスを作成し推奨値を格納した。
IG PublisherにてFixed Valueに対する警告が発生したため、Slicing(valueSetを利用しない）方法での回避を行った。
SWG2
- コメントを作成したが、内容についての可否
- Fixed Valueの回避方法（1件のValueSetを作成するよりもスマートだと思ったのでこのように修正した）

swg2 FixedValue警告回避。0..1のスライスを作成し推奨値を格納した

---

input/fsh/profiles/JP_DiagnosticReport_Radiology.fsh
input/fsh/terminologies/JP_DiagnosticReportRadiologyCode_VS.fsh

Codeの推奨値ををValueSetではなくSlicingにより提示
１件のValueSetは本来の使い方ではないため、Slicingを使った提示に変更した。
LabResultについも同様の修正にあわせた。
SWG2
- 日本語の記述部分等

SWG2 Codeの推奨値ををValueSetではなくSlicingにより提示

---

input/fsh/profiles/JP_DiagnosticReport_Radiology.fsh
input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-notes.md

MustSupport記述の変更
DiagnosticReportRagiologyのMustSupport記述
以下にMS属性を付与
basedOn , category, effective[x], performer, resultInterpreter
swg2
MS属性付与についてご確認ください。
categoryは必須なのでcard 1..1でMS属性で良いのかと思いますが、別の指定方法があればお教えください。
fixed #447

MustSupport記述の更新

---

input/fsh/profiles/JP_ImagingStudy_Radiology.fsh
input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md

identifierはDICOM画像が存在する際にsutdy instance UIDが格納されることを必須とする（Must Support)のため、fshの記載、noteの記載を誤解のないように修正した。
swg2
画像が存在する場合という前提条件が判りにくかったと思われますので、fshでidentifierをMS設定し、内容にStudy instance UIDに関する記載と、その他オプションの記載を追加しました。
また、notesにMust Supportの項を新設し、identifierに関する記述を追加しました。
ご確認ください。
fixed #475

fsh, notesのidentifier記述をupdate

---

input/fsh/profiles/JP_Medication.fsh

formの説明をMERIT9ベースの変更
FHIR BASEの説明が残っていたため。
SWG5
- 内容に不整合等がないか。
- 今回注射のみの利用なので、記述としてもう少し説明を加えなくて大丈夫か。
fixed #479
[ビルド結果](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg5-Medicaion_form%E3%81%AE%E8%AA%AC%E6%98%8E%E3%81%8C%E7%95%B0%E3%81%AA%E3%82%8B/StructureDefinition-jp-medication.html#profile)

swg5-formの説明をMERIT9ベースの変更

---

input/intro-notes/StructureDefinition-jp-diagnosticreport-endoscopy-notes.md
input/intro-notes/StructureDefinition-jp-imagingstudy-endoscopy-notes.md

- 「注意事項」のセクションの中のサブセクションの見出しの要素名をcamel形式に統一 
　　(text, code, categoryがそれぞれ先頭が大文字だったのを是正)
- ImagingStudyの「注意事項」セクションの中の「Mappings」サブセクションの見出しを
　「マッピング」に変更 (要素名でないため混乱せぬよう日本語化)
- DiagnosticReport Endoscopyの、SearchParameter一覧にて、以下のURL書式を修正
- based-on
- conclusionCode
@findex-miyakawa 
fixed #510

内視鏡のマークダウンの内容修正

---

input/fsh/profiles/JP_MedicationRequest.fsh
input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md

JP_MedicationRequest, JP_MedicationRequest_Injectionに間違って preparation 拡張が残っていたため削除する
SWG4-5
@skoba 
修正内容が正しくProfileとMDに反映されているか

JP_MedicationRequest, _Injectionからpreparationを削除する

---

.github/workflows/develop.yaml
input/intro-notes/StructureDefinition-jp-imagingstudy-endoscopy-notes.md
input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md

series.modalityに関する検索について記述の見直しを行った
@HERMITRION 
ImagingStudyのmodalityの検索ですが、
https://www.hl7.org/fhir/R4/searchparameter-registry.html
のImagingStudy-modalityにヒットする列にあるのですが、既に定義済みの検索パラメーターにmodalityとして登録されており、その対象はSeries.modalityになっています。
複雑なのですが、Imaging.modalityを検索するには、別途FHIR.PATH等で指摘するか、あらたにSearchParameterを作成してjp-Imagingstudy-modality等を定義することになりそうです。
ImagingStudy.modalityについては重要な項目ではないため、これに合わせて修正を行いました。

series.modalityに関する検索について記述の見直しを行った

---

input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-notes.md

codeとcategoryの内容がLOINCへのリンクとして記述されていたので、JP Coreのリンクへ記述を変更
codeとcategoryの使い分けの意義について追記した
SWG2
記述の修正と追加に留めているが、リンクが正しく動作するか確認が必要

DiagnosticReport-radiologyにcodeとcategoryについての記述を追加

---

input/fsh/examples/JP_Observation_LabResult_Example.fsh
input/intro-notes/StructureDefinition-jp-observation-common-notes.md

本WGの深川さんによる以下の修正分です
- containedのtext☑生化学検査 ※”尿検査"ではないので修正
- codeのtext☑尿酸 "検査項目コード"ではないので修正
- interpretationのtext☑H 高値のほうが疾患をイメージしやすいので修正 + coding部分も高値へ
- referenceRangeのlow/high☑2.1-7 日本的な基準値に修正（人間ドック学会参照）
- valueQuantityのvalue☑8.5 高値のほうが疾患をイメージしやすいので修正
- occurenceDateTimeとeffectiveDateTime☑2021-10-19T01:15:00+09:00,2021-10-19T02:20:00+09:00 ※自然な日本時間に修正
@findex-miyakawa 
修正先のブランチが間違っていないか

JP Core Observation LabResult ProfileのExampleを修正（深川さん修正分）

---

input/intro-notes/StructureDefinition-jp-observation-labresult-notes.md

検体検査結果の例として「尿」と書かれていましたが、リンク先は「尿酸」なので修正しました。
SWG2か宮川さん
誤字の確認とmerge先をご検討ください

fixed typo:尿 -> 尿酸

---

.github/workflows/develop.yaml
.github/workflows/main.yaml

第15回医療オープンソースソフトウェア協議会セミナーに参加させていただいたものです。
リポジトリを拝見して、contributeできそうなところを見かけたためPR送らせていただいています。
GitHub Actionsで使っているactionが古く、Node 16を使っていることに起因する警告が出ておりましたので、各actionsを更新しています。更新にはbreaking changeがないことを確認済みです。
また [`set-output` は2022年から非推奨となっています](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)ので、`$GITHUB_OUTPUT` で置き換えたほうが良いのではと思いました。
不明です。お手数おかけしますがアサインいただけると助かります。
forkしたリポジトリではSTEP1以降のstepが動作しないため、動作確認は不十分な状態です。
大きな問題はないはずですが、一度こちらのPR内でworkflowを実行いただくほうが安全だと思います（権限をお持ちの方に実行いただければSecretsにアクセス可能なはず）。
該当なし。
特にありません。よろしくお願いいたします。

GitHub Actionsで使っているactionを更新

---

input/fsh/profiles/JP_Observation_Radiology_Impression.fsh
input/fsh/terminologies/JP_DICOMModality_VS.fsh
input/fsh/terminologies/JP_ObservationRadiologyCode_VS.fsh
input/includes/markdown-link-references.md
input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-notes.md

宮川さん指摘のエラーの修正
SWG2
VS関連のurl修正および一部typoの修正
url表記の齟齬についてのエラーは残っていますが、VSのidとurlについて他のリソースと同様の命名規則で記述しているにも関わらずエラーが残ります。urlを小文字にしてidと合わせると解決する話と思いますが、swg45の守備範囲と思われますのでそのままにしてあります。

url エラーの修正

---

input/fsh/profiles/JP_MedicationAdministration.fsh
input/fsh/profiles/JP_MedicationRequest.fsh
input/fsh/profiles/JP_MedicationStatement.fsh

#568 に対応するためmedicationReferenceに下記definitionを追加。
``
医薬品の識別情報は必須でありmedicationReference.referenceが必ず存在しなければならない、JP Coreでは注射の医薬品情報は単一薬剤の場合も Medicationリソースとして記述し、medicationCodeableConceptは使用しない。参照するMedicationリソースは、MedicationRequest.contained属性に内包することが望ましいが、外部参照としても良い。
``
SWG45
definitionのつける一。
Fixed #568

medicationReferenceにdefinitionを追加

---

_genonce.bat
input/fsh/examples/JP_DiagnosticReportDentalOral_Example.fsh
input/fsh/examples/JP_DiagnosticReportEndoscopy_Example_1.fsh
input/fsh/examples/JP_DiagnosticReportEndoscopy_Example_2.fsh
input/fsh/examples/JP_DiagnosticReportLabResult_Example.fsh
input/fsh/examples/JP_DiagnosticReportMicrobiology_Example.fsh
input/fsh/examples/JP_DiagnosticReportRadiology_Example.fsh
input/fsh/examples/JP_Observation_BodyMeasurement_Example.fsh
input/fsh/examples/JP_Observation_Endoscopy_Diagnosis_Example_1.fsh
input/fsh/examples/JP_Observation_Endoscopy_Diagnosis_Example_2.fsh
input/fsh/examples/JP_Observation_Endoscopy_Findings_Example_1a.fsh
input/fsh/examples/JP_Observation_Endoscopy_Findings_Example_1b.fsh
input/fsh/examples/JP_Observation_Endoscopy_Findings_Example_2a.fsh
input/fsh/examples/JP_Observation_Endoscopy_Findings_Example_2b.fsh
input/fsh/examples/JP_Observation_LabResult_Example.fsh
input/fsh/examples/JP_Observation_PhysicalExam_Example.fsh
input/fsh/examples/JP_Observation_SocialHistory_Example.fsh
input/fsh/examples/JP_Observation_VitalSigns_Example.fsh
input/fsh/profiles/JP_DiagnosticReport_DentalOral.fsh
input/fsh/profiles/JP_DiagnosticReport_Endoscopy.fsh
input/fsh/profiles/JP_DiagnosticReport_LabResult.fsh
input/fsh/profiles/JP_DiagnosticReport_Microbiology.fsh
input/fsh/profiles/JP_DiagnosticReport_Radiology.fsh
input/fsh/profiles/JP_Observation_BodyMeasurement.fsh
input/fsh/profiles/JP_Observation_Endoscopy.fsh
input/fsh/profiles/JP_Observation_LabResult.fsh
input/fsh/profiles/JP_Observation_Microbiology.fsh
input/fsh/profiles/JP_Observation_PhysicalExam.fsh
input/fsh/profiles/JP_Observation_SocialHistory.fsh
input/fsh/profiles/JP_Observation_VitalSigns.fsh

Observation, DiagnosticReports familyのcategoryについてのネーミングルールを下記のように統一した。
|階層|slice名|
| --- | --- |
| 1 | first |
| 2 | second |
| 3 | third |
SWG2
特にエラーが出ていなければいいと思います。
fixed #671

categoryのslicingに対してのネーミングルールを統一化した。

---

input/intro-notes/StructureDefinition-jp-patient-notes.md

医療機関OID番号10桁
→
xxxxxxxx.1+医療機関コード10桁
に変更した。

PatientIdに利用する医療機関OIDの表記方法を変更した

---

input/fsh/profiles/JP_MedicationRequest.fsh

医療機関ごとの処方箋IDをSlicingを別にして規定した
fixed #724

医療機関ごとの処方箋IDをできない不具合に対応

---

.github/workflows/develop.yaml
input/intro-notes/StructureDefinition-jp-patient-notes.md

`input/fsh/StructureDefinition-jp-patient-notes.md` に以下の修正を加えた：
- #758（line25）：`nameRepresentationUse` の説明文にローマ字表記の識別が含まれていなかったため、「漢字・カナ・ローマ字表記を識別するために使用する」と表現を修正。
SWG3
- nameRepresentationUse の説明が実運用を適切にカバーしているか
- 表記の網羅性と簡潔さのバランスが取れているか
fixed #758

fix(#758): nameRepresentationUseの説明文にローマ字表記の識別も明記

---

input/fsh/examples/JP_Patient_Example.fsh

`input/fsh/JP_Patient_Example.fsh` の以下の内容を修正した：
- #755（line26）：postalCode の記述 `"1600023"` を `"160-0023"` に修正。説明文の記載内容と整合性を持たせた。
SWG3
- postalCode の記述形式として `"160-0023"` が適切かどうか
- 説明と例の整合性が確保されているか
fixed #755

fix(#755): postalCodeの値を '1600023' から '160-0023' に修正
