jami-fhir-jp-wg/jp-core-v1x

- input/fsh/codesystems/EventStatus.fsh
- input/fsh/codesystems/ObservationPhysicalExamCodes.fsh
- input/fsh/codesystems/ProcedureCodes.fsh
- input/fsh/valuesets/EventStatus.fsh
- input/fsh/valuesets/ProcedureCodes.fsh
- script/resource_publisher.rb
> Feature/swg1 codessystem valueset出力対応

- .github/workflows/develop.yaml
- input/landing_page/_index.yml
- input/pagecontent/index.md
- sushi-config.yaml
pull requestの結果にブランチ名称を追加
グループ名に空白を削除
swg1
なし
なし
> Feature/swg1 ビルド結果の変更

- input/fsh/profiles/JP_MedicationDispense_Injection.fsh
https://github.com/jami-fhir-jp-wg/jp-core-v1x/actions/runs/2118084953
short,definitionの階層に違いによるエラーを解消
【修正前】
* ^short = ・・・
* ^definition = ・・・
【修正後】
* . ^short = ・・・
* . ^definition = ・・・
SWG5
kazuhiko-ohe
コンパイルエラーになって
確認お願いします。
> short,definitionの階層に違いによるエラーを解消

- input/fsh/profiles/JP_MedicationRequestBase.fsh
用法がJAMI１桁コードでも２桁コードでもよくなったことに対応した。
> added slicing to  dosageInstruction.method.coding

- input/fsh/profiles/JP_FamilyMemberHistory.fsh
JP_FamilyMemberHistory.fsh を追加
SWG4 
develop（SWG4 ）
ローカルのSUSHIコンパイルでエラーなし
> JP_FamilyMemberHistory追加

- input/fsh/searchparameters/JP_Patient_SP.fsh
- input/includes/markdown-link-references.md
- input/pagecontent/group-searchParameter.md
- sushi-config.yaml
SWG1
SWG1
- 追加する機能として適切であること。
- 説明の記述が適切であること。
> カナでのソート用SearchParameter定義を追加しました。

- input/fsh/profiles/JP_Immunization.fsh
slice命名規則、urlにhttpsが混入、不要な定義の削除
SWG1
SWG5
命名規則等を変更しております。確認をお願いします。
> Immunizationの修正。

- input/pagecontent/group-medication.md
- input/pagecontent/index.md
Immunizationリソースを、index.md, group-xxx.mdへ追加した。
SGW1
SGW5
・xxx-intro.mdおよびxxx-notesの記載は無くても大丈夫でしょうか？
fixed #113 
fixed #114
> ImmunizationリソースのMakrdown文書への反映

- input/fsh/profiles/JP_Encounter.fsh
- input/intro-notes/StructureDefinition-jp-encounter-notes.md
> 参照先をJP Coreのリソースに変更した。

- input/fsh/profiles/JP_Immunization.fsh
- input/fsh/profiles/JP_Medication.fsh
- input/fsh/profiles/JP_MedicationAdministration.fsh
- input/fsh/profiles/JP_MedicationAdministration_Injection.fsh
- input/fsh/profiles/JP_MedicationDispense.fsh
- input/fsh/profiles/JP_MedicationDispenseBase.fsh
- input/fsh/profiles/JP_MedicationDispense_Injection.fsh
- input/fsh/profiles/JP_MedicationRequest.fsh
- input/fsh/profiles/JP_MedicationRequestBase.fsh
- input/fsh/profiles/JP_MedicationRequest_Injection.fsh
DescriptionとPurposeで重複していたのでpurposeをコメントアウト
SWG5
@skoba 
漏れがないかどうか
> commented out refs #130

- .github/workflows/develop.yaml
- input/landing_page/_index.yml
github pageのindexにpull requestタイトルを追加
swg1
swg1
> pullRequestのタイトル取得

- input/fsh/profiles/JP_MedicationAdministration.fsh
- input/fsh/profiles/JP_MedicationRequestBase.fsh
extensionのvalue型を厳密化してみました。
ご検討ください。
SWG5
・処方箋情報との整合性があっているのかは気になります。
> SWG5: extensionの値の厳密化をしました。

- input/fsh/terminologies/JP_ProcedureBodySite_CS.fsh
- input/fsh/terminologies/JP_ProcedureBodySite_VS.fsh
- input/fsh/terminologies/JP_ProcedureCodesDental_CS.fsh
- input/fsh/terminologies/JP_ProcedureCodesDental_VS.fsh
- input/fsh/terminologies/JP_ProcedureCodesICHI_CS.fsh
- input/fsh/terminologies/JP_ProcedureCodesICHI_VS.fsh
- input/fsh/terminologies/JP_ProcedureCodesMedical_CS.fsh
- input/fsh/terminologies/JP_ProcedureCodesMedical_VS.fsh
- input/fsh/terminologies/JP_ProcedureCodesNurse_CS.fsh
- input/fsh/terminologies/JP_ProcedureCodesNurse_VS.fsh
- input/fsh/terminologies/JP_ProcedureCodesSTEM7_CS.fsh
- input/fsh/terminologies/JP_ProcedureCodesSTEM7_VS.fsh
- input/fsh/terminologies/JP_ProcedureConditionCodes_CS.fsh
- input/fsh/terminologies/JP_ProcedureConditionCodes_VS.fsh
タイプミス(procesure → procedure)
SWG4
宜しくお願いします。
> SWG4: procesure→procdureへの修正

- input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md
リンクにアンカーを付けるように変更。バインディング情報削除
SWG1
SWG5
・リンク先が正しいか。
> swg5 リンクにアンカーを付けるように変更。バインディング情報削除

- input/intro-notes/StructureDefinition-jp-immunization-notes.md
- input/intro-notes/StructureDefinition-jp-medication-notes.md
- input/intro-notes/StructureDefinition-jp-medicationadministration-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationadministration-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md
タイプミスのチェックを行いましたので確認をお願いします。
SWG5
- 変更内容に問題がないか。
> swg5 タイプミスチェック

- input/fsh/aliases-jpcore.fsh
- input/fsh/examples/JP_DiagnosticReportRadiology_Example.fsh
- input/fsh/examples/JP_ImagingStudyRadiology_Example.fsh
- input/includes/markdown-link-references.md
- input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md
inlineになっていたImageStudyRadiologyをexampleに昇格させた。
SWG2
- サンプルファイルとして適切かどうか
fixed #200
> swg2 ImageStudyRadiologyのサンプル追加

- input/fsh/examples/JP_AllergyIntolerance_Example.fsh
- input/fsh/examples/JP_Condition_Example.fsh
- input/fsh/examples/JP_FamilyMemberHistory_Example.fsh
- input/fsh/examples/JP_Procedure_Example.fsh
- input/includes/markdown-link-references.md
- input/intro-notes/StructureDefinition-jp-allergyintolerance-notes.md
- input/intro-notes/StructureDefinition-jp-condition-notes.md
- input/intro-notes/StructureDefinition-jp-familymemberhistory-notes.md
- input/intro-notes/StructureDefinition-jp-procedure-notes.md
- サンプルのタイトルに日本語を加えた
- 説明文書の中にサンプルのリンクを追加した。
SWG4
- リンク等が正しく動作するか。
> swg4 サンプル関連微修正

- input/intro-notes/StructureDefinition-jp-coverage-notes.md
- input/intro-notes/StructureDefinition-jp-encounter-intro.md
- input/intro-notes/StructureDefinition-jp-location-notes.md
- input/intro-notes/StructureDefinition-jp-organization-notes.md
- input/intro-notes/StructureDefinition-jp-practitionerrole-notes.md
スペルミスの確認を行った
SWG3
- 修正点に問題ないか。
> swg3 スペルチェックを行った

- input/fsh/aliases.fsh
- input/fsh/examples/JP_Patient_Example.fsh
- input/fsh/profiles/JP_Patient.fsh
- JP_Patient_RaceをCadableConcept型へ変更
- Coding部分に対してバンディングを行った
- Extension部分にはSlice定義は不要のため削除
SWG3
- Race
fixed #191
> SWG3 JP_Patient_RaceをCadableConcept型へ変更、バインディングの付与

- input/fsh/profiles/JP_MedicationRequest.fsh
- input/fsh/profiles/JP_MedicationRequestBase.fsh
Cardinality部分にorderInRpが残っていたので修正
swg5
containsは単独表記で追加となるかどうか。
Identifier[orderInRp]だけではなく，JP_MedicationRequestBaseで規定されているIdentifier[rpNumber]やidentifier[requestIdentifier]も含まれるかどうか。
#236\
　
> moved cardinality refs #236

- input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh
- input/fsh/examples/JP_MedicationDispense_Injection_Example.fsh
- input/fsh/examples/JP_MedicationRequest_Injection_Example.fsh
- input/fsh/examples/JP_Medication_Example.fsh
- https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/251
- SWG5
- MedicationRequest_InjectionのサンプルインスタンスからorderInRpのスライスを削除しました。
- 各種Medication系サンプルインスタンスの単位コードがMERIT-9と異なっておりましたので、修正しました。
- 回: KAI → TIME
> SWG5 サンプルインスタンスからorderInRpを削除した

- input/intro-notes/StructureDefinition-jp-medication-notes.md
- input/intro-notes/StructureDefinition-jp-medicationadministration-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
MERIT-9のコード「KAI」を「TIME」に変更する
SWG5 @skoba 
「KAI」がすべて「TIME」に変更されているか
fixed #271
> MERIT-9のコード「KAI」を「TIME」に変更する

- input/intro-notes/StructureDefinition-jp-observation-common-notes.md
jp-core-v1x/input/intro-notes/StructureDefinition-jp-observation-common-notes.md　の検索パラメータの例示に補足説明を追記
平山さんお願いします！
GITのお試し的な修正です。1.1に不可欠な修正ではありません。
> SWG2 Observation common の注意文書にて、検索パラメータの例示に補足説明を追記

- input/intro-notes/StructureDefinition-jp-immunization-notes.md
ImmunizationのExtension名やURL、TYPO修正
SWG5
- fshファイル側に名称やURLを合わせました。
> swg5 Immunization Extension名やURL、TYPO修正

- input/fsh/profiles/JP_MedicationRequest.fsh
JP_MedicationRequest.rate[x] → rateRatioに変更する。
IGのエラーが解消する
※すでに薬剤コードについてのエラーがDevelopで解消していたので、Pull Requestの内容を変更しました。
swg5
- errorが0件になっているか。
- warningが増えていないか
> swg5 JP_MedicationRequest.rate[x]の指定方法の変更

- input/fsh/examples/JP_ImagingStudyRadiology_Example.fsh
- input/intro-notes/StructureDefinition-jp-diagnosticreport-common-intro.md
- input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-intro.md
- input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-notes.md
featureからfetureへのマージリクエストになります。
確認し、気になった点を修正しました。
- www.hl7.org関連は、https、R4のバージョンを指定で統一
- system関連については、CodeSystemのURLになるように統一
- identifierのtypeを確認（value⇒text) ,identitifier.systemの誤りを修正
- modaityのsystemを以前のものに戻す
swg2 @HERMITRION
featureブランチに対するマージなので、権限はあると思います。
- identifier等を特に確認をお願いします。
> swg2 レビューおよび気づいた点修正

- input/intro-notes/StructureDefinition-jp-medicationadministration-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationadministration-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md
Must Support関連の記述を削除する。TBDとなっていた検索パラメータを明記する。
SWG5 @skoba 
Must Support関連の記述とTBDとなっていた検索パラメータが問題ないか。
fixed #288
fixed #255
> Must Support関連の記述を削除する

- input/fsh/terminologies/JP_MedicationSubstitutionNotAllowedReason_CS.fsh
後発品変更不可コードに「0:変更可」を追加
SWG5 @skoba 
コードの追加の可否
> コード「0:変更可」を追加

- input/fsh/profiles/JP_MedicationAdministration.fsh
SWG5 @skoba 
MedicationAdministration.statusの余計な記述の削除
ref #329
> fixed MedicationAdministration.status ref #329

- input/fsh/aliases-jpcore.fsh
- input/fsh/profiles/JP_Medication.fsh
- input/fsh/profiles/JP_MedicationAdministration.fsh
- input/fsh/profiles/JP_MedicationDispense.fsh
- input/fsh/profiles/JP_MedicationDispenseBase.fsh
- input/fsh/profiles/JP_MedicationRequest.fsh
- input/fsh/profiles/JP_MedicationRequestBase.fsh
- input/fsh/terminologies/JP_MedicationExampleLine_CS.fsh
- input/fsh/terminologies/JP_MedicationExampleLine_VS.fsh
- input/fsh/terminologies/JP_MedicationInstructionForDispenseJHSP0002_CS.fsh
- input/fsh/terminologies/JP_MedicationInstructionForDispenseJHSP0002_VS.fsh
サンプルバインディングの生成とFSHファイルへのバインディングの設定
SWG5 @skoba 
Issueでの課題が解決しているか
fixed #232
fixed #231
fixed #230
fixed #228
fixed #317
fixed #327
fixed #319
fixed #308
> サンプルバインディングの生成とFSHファイルへのバインディングの設定

- input/fsh/profiles/JP_MedicationDispenseBase.fsh
> SWG5 MedicationDispenseBase.fsh fixed refrences, refs #318

- input/fsh/capabilitystatements/JP_Client_CapabilityStatement.fsh
- input/fsh/capabilitystatements/JP_Server_CapabilityStatement.fsh
FamilyMemberHistoryおよびImmunizationプロファイルのCapabilityStatementへの追加
swg1
- capablitystatementのページに反映されているか。
- OpenAPIのファイルに反映されているか
fixed #323 
fixed #326
> swg1 FamilyMemberHistoryおよびImmunizationプロファイルのCapabilityStatementへの追加

- input/fsh/examples/JP_ImagingStudyRadiology_Example.fsh
imagingstudy Example bodySiteのコードの付替
DICOMで提供されているfreeのsnomedコードへの付け替えを行った。
swg2
- コード等に誤りがないか。
fixed #374
> swg2 imagingstudy Example bodySiteのコードの付替

- input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md
BodySiteとlateralityの項にCodeSystem利用の際の注意点を追記
特にSNOMEDとDICOM間の契約により無償利用可能である点と、CodeSystem指定時のdisplay textとの整合性についての注意を記載した
SWG2
内容の確認とエラー等のチェック
fixed #374
> swg2 BodySiteとlateralityの項にCodeSystem利用の際の注意点を追記

- input/fsh/profiles/JP_ImagingStudy_Radiology.fsh
ProcedureCodeのdescriptionがbinding強度と矛盾する点を修正
swg2
内容の確認
fixed #361
> procedureCode説明の修正 #361

- input/fsh/profiles/JP_DiagnosticReport_Radiology.fsh
DiagnosticReport_Radiology.codeをfixedValueからvalueSetへ
SWG2
- 制約を緩める方向であるが良いか再度確認をお願いします。
> swg2 DiagnosticReport_Radiology.codeをfixedValueからvalueSetへ

- input/intro-notes/StructureDefinition-jp-diagnosticreport-common-notes.md
- input/intro-notes/StructureDefinition-jp-diagnosticreport-labresult-notes.md
- input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md
- input/intro-notes/StructureDefinition-jp-observation-common-notes.md
- input/intro-notes/StructureDefinition-jp-observation-labresult-notes.md
検索パラメータでsubjectを使用している箇所をpatientに修正
@findex-miyakawa 
fixed #353
> 検索パラメータでsubjectを使用している箇所をpatientに修正

- input/fsh/aliases.fsh
- input/fsh/profiles/JP_Encounter.fsh
- input/intro-notes/StructureDefinition-jp-encounter-notes.md
identifierをSHALL,us-npiを削除,extensionの追加
SWG3
- indentifier以外のsearchparamterをshouldに変更
- fshにもextensionを追加 0..*の多重度で良いか
fixed #387
fixed #388
fixed #389
> swg3 identifierをSHALL,us-npiを削除,extensionの追加

- input/intro-notes/StructureDefinition-jp-imagingstudy-radiology-notes.md
MustSupportのseries.performer.actorの記述でバーチカルバーへのエスケープ忘れを修正
swg2
DICOMタグのOR表記であるバーチカルバーが正しく反映されていることの確認
> バーチカルバーをエスケープ

- input/intro-notes/StructureDefinition-jp-organization-notes.md
OrganizationのIdetifierの要求レベルを変更
swg3
> SWG3 OrganizationのIdetifierの要求レベルを変更

- input/fsh/profiles/JP_Organization.fsh
http://jpfhir.jp/fhir/Common/IdSystem/....　-> http://jpfhir.jp/fhir/core/IdSystem/....に修正
> JP_Organizaion.fsh line#48 Common->core

- input/fsh/profiles/JP_Procedure.fsh
code.coding[stem7]　と　code.coding[dental]のshort description記述を修正。
> code.coding[dental]関連の誤記を修正

- .github/workflows/develop.yaml
宮川さん
IG  publisherが使うhl7.fhir.core#4.0.1のpackageとして、オリジナル版ではなく
日本語に一部修正し、一部のcode binding strengthをpreferredからexampleにレベルに落としたバージョンに変える(coreパッケージでpreferredになっているbindingをjp-coreで別のvalueSetにbindingを変更していても、validaitorではwarningが出るため）
> Update for using JPmodification of hl7.fhir.core#4.0.1

- input/fsh/capabilitystatements/JP_Client_CapabilityStatement.fsh
- input/fsh/capabilitystatements/JP_Server_CapabilityStatement.fsh
- input/fsh/ruleset.fsh
Profile追加に対応
RuleSetによる記述に変更
@findex-miyakawa
> Feature/infra capablity statementの追加＆リファクタリング

- input/intro-notes/StructureDefinition-jp-diagnosticreport-labresult-notes.md
- input/intro-notes/StructureDefinition-jp-diagnosticreport-microbiology-notes.md
- input/intro-notes/StructureDefinition-jp-diagnosticreport-radiology-notes.md
- input/intro-notes/StructureDefinition-jp-observation-common-notes.md
- input/intro-notes/StructureDefinition-jp-observation-labresult-notes.md
- input/intro-notes/StructureDefinition-jp-observation-microbiology-notes.md
SearchParameter関連の修正を行った。
@kis-hirayama 
- identifierのshall追加統一
- categoryの検索例を修正
fixed #516, #517
> Feature/observation category変化に伴うmdファイルの修正

- .github/workflows/main.yaml
- custom-template/includes/fragment-pagebegin.html
- input/fsh/profiles/JP_DiagnosticReport_Common.fsh
- input/fsh/profiles/JP_DiagnosticReport_Endoscopy.fsh
- input/fsh/profiles/JP_DiagnosticReport_LabResult.fsh
- input/fsh/profiles/JP_DiagnosticReport_Microbiology.fsh
- input/fsh/profiles/JP_DiagnosticReport_Radiology.fsh
- input/fsh/profiles/JP_Encounter.fsh
- input/fsh/profiles/JP_Observation_Common.fsh
- input/fsh/profiles/JP_Observation_Microbiology.fsh
- input/fsh/ruleset.fsh
>  DiagnosticReportXXX.category関係のProfile Tree表示がおかしくなるのを修正

- .github/workflows/develop.yaml
- .github/workflows/main.yaml
- other/index.html
- other/index1_1_2.html
> releaseラベルの変更

- input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh
- input/fsh/examples/JP_MedicationDispense_Injection_Example.fsh
- input/fsh/examples/JP_MedicationRequest_Injection_Example.fsh
- input/fsh/examples/JP_MedicationStatement_Injection_Example.fsh
- input/fsh/examples/JP_Medication_Example.fsh
- input/fsh/profiles/JP_Medication.fsh
issue #567で指摘された事項の修正。
ProfileでMedication.strength.denominatorを1回(TIME)を固定にしたので、Exampleからその分を削除しました。
@tmskmr @yoshinori-kodama 
Exampleからdenominatorに関する記述を削除しないとエラーが出るので削除しました。既存のインスタンスでバリデーションエラーが出ないか家訓をお願いします。
fixed #567
これ終わんないと次の #568 にいけない。
> Swg45 fix567

- input/fsh/searchparameters/JP_Coverage_SP.fsh
- input/fsh/searchparameters/JP_MedicationRequest_SP.fsh
- input/fsh/searchparameters/JP_Organization_SP.fsh
- input/fsh/searchparameters/JP_Patient_SP.fsh
Revised the description of type conversion of searchparameter as pointed out in the issue.
fiexed #613
> modify invalid searchparameter

- input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh
- input/fsh/examples/JP_MedicationDispense_Injection_Example.fsh
- input/fsh/examples/JP_MedicationRequest_Injection_Example.fsh
- input/fsh/examples/JP_MedicationStatement_Injection_Example.fsh
- input/fsh/examples/JP_Medication_Example.fsh
maditionのstrength.denominatorの値について、消えてしまった点を修正
診療WG
修正内容が正しいか
fixed #625
> 力価の分母の記載、回の固定値に対応

- custom-template/content/assets/css/fix-fonts.css
- other/assetsOfIndex/css/fix-fonts.css
FontSizeの固定値をCSSより排除。全体を120%に拡大する。
fixed #582
> FontSizeの固定値をCSSより排除。全体を120%に拡大する。

- input/intro-notes/StructureDefinition-jp-medicationstatement-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationstatement-notes.md
> medicationStatementに対するOperation操作に対する記述を削除

- input/fsh/terminologies/JP_ObservationElectrocardiogramDuration_VS.fsh
- input/fsh/terminologies/JP_ObservationElectrocardiogramStressType_VS.fsh
- input/pagecontent/update_history.md
Fixed ElectroCardioGram -> Electrocardiogram
Added value sets and code sets to history
SWG2
Artefact summaryも修正が必要？
> Fixed typos

- input/fsh/profiles/JP_Medication.fsh
strength.denominatorの(exactly)を外して固定値とした。
SWG45
指摘されたwarningは出なくなったもののen/jaに関連するwarningがたくさんでたのでどうしたものか。
ref #664
> changed rule to fixed value

- input/intro-notes/StructureDefinition-jp-medicationstatement-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationstatement-notes.md
検索パラメータにMedicationStatementに存在しないwhenhandoverを指定していたものを削除した。
SWG5
おそらくこれで大丈夫。
fixed #650
> removed the searchparameter for whenhandover

- input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh
- input/intro-notes/StructureDefinition-jp-medicationadministration-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-injection-notes.md
- input/intro-notes/StructureDefinition-jp-medicationdispense-notes.md
- input/intro-notes/StructureDefinition-jp-medicationstatement-notes.md
- input/pagecontent/guide-urlmap.md
注射のHL70162表のURLを処方に合わせる
SWG4+5
変更したURLが正しいか
fixed #727
> 注射のHL70162表のURLを処方に合わせる

- input/fsh/examples/JP_MedicationRequest_Example.fsh
- input/fsh/examples/JP_MedicationRequest_Injection_Example.fsh
- input/fsh/invariant.fsh
- input/fsh/profiles/JP_MedicationRequest.fsh
> 施設単位の処方箋IDについて制約を追加

- input/intro-notes/StructureDefinition-jp-condition-diagnosis-notes.md
> fixed ＃790

- input/fsh/profiles/JP_Procedure.fsh
> fixed ＃742

- input/fsh/profiles/JP_Condition_Diagnosis.fsh
翻訳の該当箇所が見つからなかったので、FSHファイルに記載し上書きを試みました。
宮川さんこれどう？
この方法が有効かどうか
ref #788
> fixed ＃788

- _genonce.bat
- input/fsh/profiles/JP_Immunization.fsh
SWG45
あっても良いと思って、siteにterminology bindingを追加しました。なくてもエラーにまではならないことがレビューポイントです。
Fixed #844
> Added body site the terminology binding

- input/fsh/profiles/JP_Immunization.fsh
余分な「の」を削除
swg45
該当部位の修正ができているかどうか
fixed #841
> fixed typo

- input/fsh/profiles/JP_MedicationRequest.fsh
#814 でご指摘の件について修正した。
SWG45
若干指摘されている事項と文言の変更を行っている。
fixed #814
> fixed description ref 814

- input/fsh/profiles/JP_MedicationRequest.fsh
指摘を受けて「薬剤単位の備考」を「薬剤オーダごとの備考」に修正した
SWG45
fixed #821
> fixed description

- input/fsh/profiles/JP_MedicationRequest.fsh
#820 で指摘されたようにbasedOnの参照先を増やした。
SWG45
fixed #820
> added references

- input/fsh/profiles/JP_Observation_LabResult.fsh
> JP_Observation_LabResultのv1.2パブコメ対応

- input/intro-notes/StructureDefinition-jp-medicationrequest-notes.md
記述が古いままであったため削除した。
SWG45
fixed #830
> fixed description for order id

- input/fsh/profiles/JP_MedicationRequest.fsh
> changed descripition from the request of 833

- input/fsh/examples/JP_Organization_Example.fsh
- input/fsh/profiles/JP_Organization.fsh
- input/intro-notes/StructureDefinition-jp-encounter-notes.md
- input/intro-notes/StructureDefinition-jp-organization-notes.md
#765 医療機関コードのスライシング名称とSystem値URL名称の揺れ
SWG3
表記ゆれの統一
#765
> fix(#765):医療機関コードのスライシング名称とSystem値URL名称の揺れ
